<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sort byFeatured</name>
   <tag></tag>
   <elementGuidId>6736af71-c03f-474a-89cb-4b8d66a1e645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='a-autoid-0-announce']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-0-announce</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sort by:Featured&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61b4b7e2-3e04-473e-ae68-f8d418d87db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text a-declarative</value>
      <webElementGuid>5c9da317-5a69-4ade-8bf7-530ea0d7975a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>a-dropdown-button</value>
      <webElementGuid>28fe912d-6adc-4e4f-8df6-6193d9929671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5634314f-8cbe-4932-baca-db5c96ac42b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>3077327e-9c83-4701-8d0b-a618207b009c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sort by:Featured</value>
      <webElementGuid>dafd1afd-34b2-41f2-a036-43db7a62b2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0-announce&quot;)</value>
      <webElementGuid>1d1b4065-8cd8-4ade-b453-0251df248575</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0-announce']</value>
      <webElementGuid>0dd59dce-11ed-485b-93a3-eb71f7637189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/span</value>
      <webElementGuid>8807ded5-40b4-4035-b144-8bd465b0effd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/following::span[3]</value>
      <webElementGuid>de9085e2-e7df-4409-a36b-3e72b6bcfbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>506662c3-dc7a-478d-8198-4eab63139b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'a-autoid-0-announce' and (text() = 'Sort by:Featured' or . = 'Sort by:Featured')]</value>
      <webElementGuid>31d6fec4-8af6-4a05-9dc1-ed377b1637f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
